sonar.projectKey=fuchi-no-dokuneko_tts_visual
sonar.organization=fuchi-no-dokuneko
sonar.host.url=https://sonarcloud.io
sonar.projectName=tts_visual
sonar.sourceEncoding=UTF-8
sonar.sources=batch_runner.py,engines,utils
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
